const ordersTypes = {
SAVE_ORDER_HISTORY_START: 'SAVE_ORDER_HISTORY_START',
GET_USER_ORDER_HISTORY: 'GET_USER_ORDER_HISTORY',
SET_USER_ORDER_HISTORY: 'SET_USER_ORDER_HISTORY',
GET_ORDERS_ADMIN: 'GET_ORDERS_ADMIN',
SET_ORDERS_ADMIN: 'SET_ORDERS_ADMIN'
};

export default ordersTypes;